name: Deploy to EC2

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Environment Variables
        run: |
          echo "EC2_SSH_KEY: $EC2_SSH_KEY"
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          echo "$EC2_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem ec2-user@34.222.47.249 'cd /home/ec2-user/app && git pull'
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
