name: CICD workflow

on:
  workflow_dispatch
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore ./BlazorApp1/BlazorApp1.csproj

      - name: Build project
        run: dotnet build ./BlazorApp1/BlazorApp1.csproj --configuration Release

      - name: Publish project
        run: dotnet publish ./BlazorApp1/BlazorApp1.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ./publish