name: Trigger Deployment on Success

on:
  workflow_run:
    workflows: ["CICD workflow"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: tabortmig12

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download published-app artifact
        uses: actions/download-artifact@v2
        with:
          name: published-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_KEY }}
          package: ./published-app
